### ISSUE TITLE
Can't convert account to 3 of 3 multisig

### ISSUE THREAD

**Issue by cryptoBeliever** [nemfoundation/symbol-desktop-wallet#196]
Steps to reproduce.
1. Create an account
2. Create 4 child accounts (w1,w2,w3,w4)
3. Send funds to w1,w2,w3,w4 and do outgoing tx for all.
4. Convert w1 to multisig and add cosingers w2,w3,w4. Choose 3 as minimal removal and 3 as min approv. Send conversion.
5. Accept partial transactions on w2,w3,w4.
6. In result I can see only Fund Lock tx in confirmed transactions and account is not converted to multisig.

I tried converting to 3 of 3 couple times. Always without success.
After that, I tried to convert the same account to 2 of 2. Worked on the first attempt.

Wallets I used:

W1	TAZQPPT2M3GB7P7C4U6FATZUREFHQKARK6B4ABQJ
W2	TCR4AE4RSJWHJOERH2F66SPHP4MLKB5MRWUH6626
W3	TALVGWCC7CXGMVBMQRDCIJP3U7NIXHXMZJVPO2FK
W4 TA2H2N5S6XKK5U6VE2NSTYOLRUZHXN63HQSQ4PMN

Wallet version: v 0.9.6
Node: http://api-01.us-west-1.symboldev.network:3000

**Comment by meyns** [comment]
Had the same problem in 0.9.6 but for me it is fixed in 0.9.7

**Comment by decentraliser** [comment]
@cryptoBeliever is this issue still valid?

**Comment by cryptoBeliever** [comment]
@decentraliser yes. Still doesn't work.
Node: http://api-01.us-west-1.symboldev.network:3000
Wallet: https://github.com/nemfoundation/symbol-desktop-wallet/releases/download/v0.9.7-beta1/symbol.desktop.wallet.v0.9.7-beta1-www.zip

**Comment by evias** [comment]
@Wayonb did you discovery anything about this?

**Comment by Wayonb** [comment]
No, I can play around later in the week.
@cryptoBeliever If you create a 2 of 2 multisig account, can you then modify this account to convert it to 3 of 3?

**Comment by cryptoBeliever** [comment]
@Wayonb editing multisig (2of2 to 3of3) contract doesn't work too.

**Comment by evias** [comment]
@decentraliser @fboucquez this bug is related to `FeeSelector`.... it doesn't set the maxFee to 1000000 when i tell it to do so.

Adding priority to this fix.

**Comment by evias** [comment]
Additionally, the `Normal` setting of FeeSelector is set to `50000 symbol.xym`, which in the case of a multisig conversion with > 2 cosignatories, is not enough anymore (minFee 60000)

I believe it is time for the FeeSelector to calculate the size of the transaction as well.

**Comment by evias** [comment]
@cryptoBeliever A temporary fix now allows you to **set higher fees** with the fee selector.

The bug happening here is that your transaction includes a maxFee of `50000` and therefor does not suffice anymore for more than 2 cosignatories.

Please test again with `v0.9.10` and setting the fee to `Fast` and/or `Fastest`, the conversion should then work fine.

Another feature will be added in later pipeline (0.10.0) to permit **dynamic fees depending on transaction sizes and multisig configuration**.

Thank you :+1:

**Comment by cryptoBeliever** [comment]
@evias after increased to Fast (0.1 XYM) it works.
Thank you :)
